spring:
  datasource:
    hikari:
      jdbc-url: jdbc:sqlite:memory:myDb?cache=shared
      driver-class-name: org.sqlite.JDBC
      username: sa
      password: sa
  jpa:
    hibernate:
      ddl-auto: update # validate
    show-sql: true
    database-platform: io.github.starrybleu.sideproject0.config.SQLiteDialect